CREATE TABLE WAREHOUSES (
    WAREHOUSE_NAME VARCHAR2(30)
    , LAT NUMBER
    , LON NUMBER
);

CREATE TABLE STORES (
    STORE_NAME VARCHAR2(30)
    , ZIPCODE VARCHAR2(5)
    , LAT NUMBER
    , LON NUMBER
    , STORE_TYPE VARCHAR2(30)
);

CREATE TABLE EARTHQUAKES (
    ID VARCHAR2(30)
    , TIME TIMESTAMP(6)
    , LAT NUMBER(38,7)
    , LON NUMBER(38,7)
    , EQDEPTH NUMBER(38,3)
    , MAG NUMBER(38,3)
    , MAGTYPE VARCHAR2(100)
    , NST NUMBER
    , GAP NUMBER
    , DMIN NUMBER
    , RMS NUMBER
    , NET VARCHAR2(100)
    , UPDATED TIMESTAMP(6)
    , PLACE VARCHAR2(255)
    , EQTYPE VARCHAR2(100)
    , HORIZONTALERROR NUMBER
    , DEPTHERROR NUMBER
    , MAGERROR NUMBER
    , MAGNST NUMBER
    , STATUS VARCHAR2(100)
    , LOCATIONSOURCE VARCHAR2(100)
    , MAGSOURCE VARCHAR2(100)
);